
[workspace]
members = [
  "_125_验证回文串"
]

[package]
name = "weykon-leetcode-cn"
version = "0.1.0"    
authors = ["Weykon <weykon@qq.com>"]

[dependencies]
regex = "1"
toml = "0.7.2"
serde = { version = "1.0.152", features = ["derive"] }